name: '@wpay/frames build'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/

      - name: NPM install
        run: npm install

      - name: NPM test
        run: npm run test

      - name: NPM Build
        run: npm run dist

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag and Release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/tag.sh
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git push
          git push --tags
